# These are supported funding model platforms

github: [DukeBode] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
tidelift: pypi/yiban # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ['https://DukeBode.github.io','https://dukebode.gitee.io'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
